### ISSUE TITLE
Installation error (conda)

### ISSUE THREAD

**Issue by mushroomOK** [Jwindler/AutoHiC#11]
Hi, according to the conda installation process, I made an error at "conda env create -f autohic.yaml". The error is as follows:
Executing transaction: | b'By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html\n'                                                                                                       done
Ran pip subprocess with arguments:
['/public3/home/scb9766/.conda/envs/autohic/bin/python', '-m', 'pip', 'install', '-U', '-r', '/public3/home/scb9766/soft/AutoHiC/condaenv.4p1kidx4.requirements.txt']
Pip subprocess output:
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting addict==2.4.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting charset-normalizer==3.1.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/33/97/9967fb2d364a9da38557e4af323abcd58cc05bdd8f77e9fd5ae4882772cc/charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 kB 2.3 MB/s eta 0:00:00
Collecting click==8.1.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorama==0.4.6
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting filelock==3.12.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ad/73/b094a662ae05cdc4ec95bc54e434e307986a5de5960166b8161b7c1373ee/filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting fsspec==2023.5.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/4e/397b234a369df06ec782666fcdf9791d125ca6de48729814b381af8c6c03/fsspec-2023.5.0-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.1/160.1 kB 2.3 MB/s eta 0:00:00
Collecting hic-straw==1.3.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8e/ec/431c76970f8973ea5937a9b5f2d1689a641b3fe6475246a32451274fa2dd/hic-straw-1.3.1.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
      /public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      ERROR: Exception:
      Traceback (most recent call last):
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
          yield
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
          data = self._fp_read(amt) if not fp_closed else b""
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
          return self._fp.read(amt) if amt is not None else self._fp.read()
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
          data = self.__fp.read(amt)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/http/client.py", line 463, in read
          n = self.readinto(b)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/http/client.py", line 507, in readinto
          n = self.fp.readinto(b)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/socket.py", line 704, in readinto
          return self._sock.recv_into(b)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/ssl.py", line 1242, in recv_into
          return self.read(nbytes, buffer)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/ssl.py", line 1100, in read
          return self._sslobj.read(len, buffer)
      socket.timeout: The read operation timed out

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
          status = run_func(*args)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 170, in run
          requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
          result = self._result = resolver.resolve(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
          super().__init__(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
          self.dist = self._prepare()
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
          dist = self._prepare_distribution()
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
          local_file = unpack_url(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
          file = get_http_url(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
          from_path, content_type = download(link, temp_dir.path)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/network/download.py", line 147, in __call__
          for chunk in chunks:
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
          for chunk in response.raw.stream(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
          data = self.read(amt=amt, decode_content=decode_content)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
          raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/contextlib.py", line 137, in __exit__
          self.gen.throw(typ, value, traceback)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
          raise ReadTimeoutError(self._pool, None, "Read timed out.")
      pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
      Traceback (most recent call last):
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/public3/home/scb9766/.conda/envs/autohic/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1ttb4jhq', '--quiet', 'pybind11>=2.4']' returned non-zero exit status 2.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xzo_gzll/hic-straw_ed8afd254b414e379963ae13223f25ac/setup.py", line 106, in <module>
          setup(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/public3/home/scb9766/.conda/envs/autohic/lib/python3.9/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/public3/home/scb9766/.conda/envs/autohic/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1ttb4jhq', '--quiet', 'pybind11>=2.4']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

CondaEnvException: Pip failed

**Comment by Jwindler** [comment]
This appears to be an installation error, and we recommend running it with Docker first. I cannot determine what went wrong from the error information you have provided so far. Can you provide a more detailed error log, including the platform you are using, to help me troubleshoot. Thank you very much.

In my experience, this may be due to a missing system library file. You can check the output carefully to see if there is an `XX is not found`

**Comment by mushroomOK** [comment]
Thanks. Docker is work.
