### ISSUE TITLE
How to resume operation after interruption.

### ISSUE THREAD

**Issue by sip123a** [Jwindler/AutoHiC#22]
Hi.
      Thank you very much for developing the software. 
      When I ran autohic and finally generated the autohic_results directory, I suddenly got an error due to insufficient memory. The first steps of autohic, juicer and 3d-dna, have been completed. When the computing node is re-modified or the CPU is changed, the operation will start from scratch. I dont't want to run juicer from  again, it takes too much time.  
      I would like to ask how I can generate a complete autohic_result directory from the second step of the interruption. Or should I use the .assembly file in which directory to run onehic.py?The following is my log output.Thank you very much.

```

[2024-04-11  16:00:59] autohic.py -> whole line:33 [INFO] : AutoHiC start running ...

[2024-04-11  16:00:59] autohic.py -> whole line:35 [INFO] : Get configuration items

[2024-04-11  16:00:59] autohic.py -> whole line:55 [INFO] : Check if the GPU is available
[2024-04-11  16:00:59] autohic.py -> whole line:59 [INFO] : GPU is not available, AutoHiC will run on CPU

[2024-04-11  16:00:59] autohic.py -> whole line:70 [INFO] : Fastq file number is correct.

[2024-04-11  16:00:59] autohic.py -> whole line:87 [INFO] : Check genome length whether > 80 base
[2024-04-11  16:00:59] autohic.py -> whole line:103 [INFO] : Genome len < 80 base

[2024-04-11  16:00:59] autohic.py -> whole line:106 [INFO] : Stage 1: Run Juicer and  3d-dna
[2024-04-12  08:32:04] autohic.py -> whole line:110 [INFO] : Run Juicer and  3d-dna finished

[2024-04-12  08:32:04] autohic.py -> whole line:113 [INFO] : Stage 2: Select the min error number of  hic file

[2024-04-12  08:32:04] autohic.py -> whole line:128 [INFO] : Check the 0 file
[2024-04-12  08:32:04] mul_gen_png.py -> mul_process line:49 [INFO] : Multiple Process Initiating ...

[2024-04-12  08:32:04] hic_adv_model.py -> __init__ line:30 [INFO] : Base Model Initiating

[2024-04-12  08:32:04] hic_adv_model.py -> __init__ line:40 [INFO] : Create genome folder: /public/home/off/project/02_mugua/07.autohic/AutoHiC/autohic_results/0/png

[2024-04-12  08:32:04] mul_gen_png.py -> mul_process line:56 [INFO] : Number of processes is : 90

Genome each line length:  60
[2024-04-12  08:32:05] hic_adv_model.py -> get_chr_len line:63 [INFO] : Hic file sequence length is : 353045643

[2024-04-12  08:32:12] mul_gen_png.py -> mul_process line:120 [INFO] : Multiple process finished

[2024-04-12  08:32:12] get_cfg.py -> get_ratio line:49 [INFO] : Ratio(assembly length / hic length) is 1.0

[2024-04-12  08:32:12] get_cfg.py -> get_hic_real_len line:105 [INFO] : Hic file real len: 353045643

[2024-04-12  08:32:12] autohic.py -> whole line:142 [INFO] : Detect the 0 file
/public/home/off/mambaforge/envs/autohic/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180487213/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/public/home/off/biosoft/AutoHiC/src/models/swin/mmdet/datasets/utils.py:64: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
/public/home/off/biosoft/AutoHiC/src/models/swin/mmdet/models/roi_heads/bbox_heads/bbox_head.py:353: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/utils/tensor_new.cpp:201.)
  scale_factor = bboxes.new_tensor(scale_factor).unsqueeze(1).repeat(
[2024-04-12  09:24:53] error_pd.py -> de_diff_overlap line:436 [INFO] : Filter all error category Done
[2024-04-12  09:24:53] error_pd.py -> chr_len_filter line:479 [INFO] : KeyError: translocation not in errors_dict
[2024-04-12  09:24:53] error_pd.py -> chr_len_filter line:479 [INFO] : KeyError: inversion not in errors_dict
[2024-04-12  09:24:53] error_pd.py -> loci_zoom line:513 [INFO] : zoom threshold: 0
[2024-04-12  09:24:53] error_pd.py -> loci_zoom line:527 [INFO] : KeyError: translocation not in errors_dict
[2024-04-12  09:24:53] error_pd.py -> loci_zoom line:527 [INFO] : KeyError: inversion not in errors_dict
[2024-04-12  09:24:53] error_pd.py -> divide_error line:558 [INFO] : Divide all error category Done
[2024-04-12  09:24:53] error_pd.py -> json_vis line:722 [INFO] : Done loading json file.
[2024-04-12  09:24:54] autohic.py -> whole line:147 [INFO] : Detect the 0 file finished

[2024-04-12  09:24:54] autohic.py -> whole line:165 [INFO] : The 0 file done

[2024-04-12  09:24:54] autohic.py -> whole line:128 [INFO] : Check the 1 file
[2024-04-12  09:24:54] mul_gen_png.py -> mul_process line:49 [INFO] : Multiple Process Initiating ...

[2024-04-12  09:24:54] hic_adv_model.py -> __init__ line:30 [INFO] : Base Model Initiating

[2024-04-12  09:24:54] hic_adv_model.py -> __init__ line:40 [INFO] : Create genome folder: /public/home/off/project/02_mugua/07.autohic/AutoHiC/autohic_results/1/png

[2024-04-12  09:24:54] mul_gen_png.py -> mul_process line:56 [INFO] : Number of processes is : 90

img size:  (1116, 1116)
Traceback (most recent call last):

  File "/public/home/off/biosoft/AutoHiC/autohic.py", line 383, in <module>
    typer.run(whole)

  File "/public/home/off/biosoft/AutoHiC/autohic.py", line 134, in whole
    mul_process(hic_file_path, "png", adjust_path, "dia", int(cfg_data["N_CPU"]))

  File "/public/home/off/biosoft/AutoHiC/src/common/mul_gen_png.py", line 57, in mul_process
    pool = Pool(process_num)  # process number

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/public/home/off/mambaforge/envs/autohic/lib/python3.9/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()

OSError: [Errno 12] Cannot allocate memory

```

**Comment by Jwindler** [comment]
Based on your log, it appears that AutoHiC is still running. However, due to memory issues, the entire AutoHiC process needs to be rerun even though Juicer has completed. Please note that all previously generated result files must be deleted before rerunning. Since AutoHiC has not fully checked all Juicer results, it is unclear which results should be used with onehic. I recommend increasing the memory and rerunning AutoHiC.

**Comment by sip123a** [comment]
Thanks for your reply. I then deleted the file and ran it again, and output some results. My hic signal was not good. I wonder if you can help analyze the software and how can I adjust the parameters better?Thank you very much！

This is a diploid, with 9 chromosomes and a genome size of approximately 350M. I used hifiasm software to assembly contig using hifi and hic data. The following is the output of hap2.Thanks again for the software you developed.

[autohic.log](https://github.com/Jwindler/AutoHiC/files/15007835/autohic.log)
![chromosome](https://github.com/Jwindler/AutoHiC/assets/166676780/a1c4b203-4250-41dc-b7dd-b4d91907a29e)

**Comment by Jwindler** [comment]
Your log shows you set the number of 3D-DNA adjustments to 5. AutoHiC selected the second adjustment to continue correcting because this result had the fewest errors. After adjustments by AutoHiC, translocation and inversion errors have been eliminated. However, the contact heatmap could not clearly show the 9 chromosomes. This may be due to poor quality of your contig genome or Hi-C data. If you've confirmed you have 9 chromosomes, I suggest improving the quality of the contig genome or using [other tools](https://github.com/Jwindler/AutoHiC/blob/main/example/other_tools.md) to scaffold, then using [onehic](https://github.com/Jwindler/AutoHiC?tab=readme-ov-file#one-setp-autohic-optional) to optimize.

**Comment by sip123a** [comment]
Thank you very much for your prompt reply. I think my contig assembly quality is not very good, do you have any good suggestion to deal with the contig when there is only 3rd generation data and hic data? to improve the assembly. Thank you again.

**Comment by Jwindler** [comment]
If your 3rd data is HiFi, you can use the [hifiasm](https://github.com/chhylp123/hifiasm) software. If your 3rd data is ONT, you can use the [NextDenovo](https://github.com/Nextomics/NextDenovo) software. If you have both, you can use them both. You can also add HiC data while using the hifiasm software. Maybe run [CRAQ](https://github.com/JiaoLaboratory/CRAQ), then scaffold will improve.
