### ISSUE TITLE
usage  of autohic: Extending AutoHiC to other assembly software

### ISSUE THREAD

**Issue by hylu-coder** [Jwindler/AutoHiC#28]
Hi,
Sorry for bothering you again.
I'v already installed autohic sucessfully. I tested it on previous hic file generated by 3D-DNA. An error was  returned:
File  C22.p_ctg.final.hic cannot be opened for reading.
I guess that the HiC files generated by 3D-DNA may require some  further processing before they can be fully utilized.

Thank you

**Comment by Jwindler** [comment]
Thanks for your feedback. Please provide me your installation log file so that I can check it for you. According to your description, your problem may be that Juicer or 3D-DNA is not running properly.

**Comment by hylu-coder** [comment]
Thanks for your reply. I can open the hic file in Juicer-box. The installation-related screen output is in the attached file.
[autohic.log](https://github.com/user-attachments/files/17106537/autohic.log)

**Comment by Jwindler** [comment]
Your installation process is correct. can you give me your run `autohic` log file, thanks.

**Comment by hylu-coder** [comment]
Sorry I wrote a incorrect HiC file path in my previous command. After re-running onehic, a new error was returned:
Traceback (most recent call last):
  File "/data5/home/zqiang/AutoHiC/onehic.py", line 18, in <module>
    from src.common.error_pd import infer_error
  File "/data5/home/zqiang/AutoHiC/src/common/error_pd.py", line 17, in <module>
    import cv2
  File "/data5/home/zqiang/.conda/envs/autohic/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/data5/home/zqiang/.conda/envs/autohic/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/data5/home/zqiang/.conda/envs/autohic/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen: cannot load any more object with static TLS

**Comment by Jwindler** [comment]
so sorry to tell you, i have not encountered this error. you can refer to https://github.com/pytorch/pytorch/issues/2575 and https://github.com/scikit-learn/scikit-learn/issues/14485. in my opinion, you can use docker to solve it.

**Comment by Jwindler** [comment]
Closing due to no activity for 2 weeks. Feel free to reopen if any guidance is needed.
