### ISSUE TITLE
Error: undefined symbol: EVP_md2

### ISSUE THREAD

**Issue by TropicalBreeding** [Jwindler/AutoHiC#35]
Thank you for your efforts.

I conda-installed in HPC. while running, I encountered this error below. Gemini says "AutoHiC program is trying to use a function called EVP_md2 from a version of OpenSSL (3.0.0 in this case) that doesn't include that function." Any suggestions? Thanks

Traceback (most recent call last):
  File "/90daydata/spcl_sun/AutoHiC/autohic.py", line 19, in <module>
    from src.assembly.adjust_all_error import adjust_all_error
  File "/90daydata/spcl_sun/AutoHiC/src/assembly/adjust_all_error.py", line 16, in <module>
    from src.assembly.cut_errors_ctg import cut_errors_ctg
  File "/90daydata/spcl_sun/AutoHiC/src/assembly/cut_errors_ctg.py", line 15, in <module>
    from src.utils.get_cfg import get_ratio
  File "/90daydata/spcl_sun/AutoHiC/src/utils/get_cfg.py", line 17, in <module>
    import hicstraw
ImportError: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0

**Comment by Jwindler** [comment]
maybe this error should contact your hpc manager to slove. you also can use [singularity](https://github.com/Jwindler/AutoHiC?tab=readme-ov-file#singularity) to use AutoHiC.

**Comment by Jwindler** [comment]
Closing due to no activity for 2 weeks. Feel free to reopen if any guidance is needed.
