### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by George-Zhou02** [Jwindler/AutoHiC#39]
Hi, thank you very much for your software. 
I installed the software according to the instructions, but an error occurred during operation. It seemed to prompt me that a library file was missing. Did I miss any important installation step? If not, where and how should I install the library file properly?
Here is the code I ran the program
```
source /public/apps/miniconda3/etc/profile.d/conda.sh
conda activate autohic

CONFIG_FILE=/fast3/group_crf/home/b21zhouxch7/PJ3_Oryzias_pectoralis/2_9_AutoHiC/cfg-autohic.txt
OUT_LOG=/fast3/group_crf/home/b21zhouxch7/PJ3_Oryzias_pectoralis/2_9_AutoHiC/log.txt
# cd AutoHiC directory
cd /fast3/group_crf/software/AutoHiC/  

# run 
python3.9 autohic.py -c $CONFIG_FILE > $OUT_LOG 2>&1 
```

The following is the error message
```
Traceback (most recent call last):
  File "/fast3/group_crf/software/AutoHiC/autohic.py", line 20, in <module>
    from src.common.error_pd import infer_error
  File "/fast3/group_crf/software/AutoHiC/src/common/error_pd.py", line 17, in <module>
    import cv2
  File "/public3/group_crf/home/b21zhouxch7/.conda/envs/autohic/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/public3/group_crf/home/b21zhouxch7/.conda/envs/autohic/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/public3/group_crf/home/b21zhouxch7/.conda/envs/autohic/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by Jwindler** [comment]
it look likes your pc need `libGL.so.1`, maybe you can refer https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

**Comment by George-Zhou02** [comment]
Thank you for your answer. I have solved the problem mentioned above. 
Unfortunately, after I re-run the software, the following warning appears in the log.txt:
```
load checkpoint from local path: /fast3/group_crf/software/AutoHiC/src/models/cfgs/error_model.pth
The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.0.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
size mismatch for roi_head.bbox_head.0.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([4]).
size mismatch for roi_head.bbox_head.0.fc_reg.weight: copying a param with shape torch.Size([4, 1024]) from checkpoint, the shape in current model is torch.Size([12, 1024]).
size mismatch for roi_head.bbox_head.0.fc_reg.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([12]).
size mismatch for roi_head.bbox_head.1.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
size mismatch for roi_head.bbox_head.1.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([4]).
size mismatch for roi_head.bbox_head.1.fc_reg.weight: copying a param with shape torch.Size([4, 1024]) from checkpoint, the shape in current model is torch.Size([12, 1024]).
size mismatch for roi_head.bbox_head.1.fc_reg.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([12]).
size mismatch for roi_head.bbox_head.2.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
size mismatch for roi_head.bbox_head.2.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([4]).
size mismatch for roi_head.bbox_head.2.fc_reg.weight: copying a param with shape torch.Size([4, 1024]) from checkpoint, the shape in current model is torch.Size([12, 1024]).
size mismatch for roi_head.bbox_head.2.fc_reg.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([12]).
size mismatch for roi_head.mask_head.0.conv_logits.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
size mismatch for roi_head.mask_head.0.conv_logits.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([3]).
size mismatch for roi_head.mask_head.1.conv_logits.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
size mismatch for roi_head.mask_head.1.conv_logits.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([3]).
size mismatch for roi_head.mask_head.2.conv_logits.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
size mismatch for roi_head.mask_head.2.conv_logits.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([3]).
img size:  (1116, 1116)
```
However, the output seems to be quite normal. So do you have any suggestions of these warnings.
Thanks again for your help！

**Comment by Jwindler** [comment]
I have never encountered this situation before. I guess there may be an error in the installation process. It is recommended to check the installation of conda and don't forget :
`cd ./src/models/swin`
`pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple/`

**Comment by George-Zhou02** [comment]
Your advice is very helpful, thanks again！

**Comment by George-Zhou02** [comment]
Hi, I'm sorry to bother you again.
I checked my installation steps and it turns out that the **error_model.pth** file had its integrity damaged during the transfer. 
> I have never encountered this situation before. I guess there may be an error in the installation process. It is recommended to check the installation of conda and don't forget : `cd ./src/models/swin` `pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple/`

This issue has been resolved by re-downloading the file. However, when I re-ran the software, I found that the results were far worse than when **error_model.pth** was partially missing.

When **error_model.pth** was partially missing:
<img width="890" alt="image" src="https://github.com/user-attachments/assets/191df6e9-0416-4dc9-9701-da0eae9be822">
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/7ac74b5a-704d-4ec4-ab73-3725570834c9">

After Repair：
<img width="869" alt="image" src="https://github.com/user-attachments/assets/7641d5ae-3a63-4877-bb14-94eaec6f0606">
<img width="1358" alt="image" src="https://github.com/user-attachments/assets/6ab08813-7702-4284-a9f0-a13c5ba4ee9e">

Basic information: 
```
This species is a diploid(2n=48)
Expected genome size: 700M
Method used for genome assembly: ONT (60×)+ Hi-C (80×)
```
Do you have any suggestions about this？
Thank you！

**Comment by Jwindler** [comment]
You can re-run it with `NUMBER_OF_EDIT_ROUNDS=2` set to `NUMBER_OF_EDIT_ROUNDS=0` in your cfg-autohic.txt.

**Comment by George-Zhou02** [comment]
> You can re-run it with `NUMBER_OF_EDIT_ROUNDS=2` set to `NUMBER_OF_EDIT_ROUNDS=0` in your cfg-autohic.txt.

It works thank you!
