### ISSUE TITLE
How about small genome size using Hi-C data?

### ISSUE THREAD

**Issue by sunnycqcn** [Jwindler/AutoHiC#45]
Hello Developers,
Thanks for your excellent pipeline.
I used this pipeline for my plant genomes, which worked well. However, when I used it for my fungal genome, the genome size is about 45 Mb. I got the error as following:
`[2024-11-22  17:03:45] inv_adjust_v2.py -> adjust_inversion line:67 [INFO] : Needs to be moved ctg: {'>scaffold00013:::fragment_4': {'length': '86611', 'start': 14469554, 'end': 14556164}}

[2024-11-22  17:03:45] get_cfg.py -> get_ratio line:49 [INFO] : Ratio(assembly length / hic length) is 1.0

[2024-11-22  17:03:45] adjust_all_error.py -> adjust_all_error line:110 [INFO] : Start moving translocation ctg

load checkpoint from local path: /isilon/projects/J-003316_Canola-activity-10A/BLgenome/3-dna/AutoHiC/error_model.pth
img size:  (1116, 1116)
Traceback (most recent call last):

  File "/isilon/projects/J-003316_Canola-activity-10A/BLgenome/3-dna/AutoHiC/autohic.py", line 383, in <module>
    typer.run(whole)

  File "/isilon/projects/J-003316_Canola-activity-10A/BLgenome/3-dna/AutoHiC/autohic.py", line 225, in whole
    black_num_list = adjust_all_error(hic_file_path, asy_file_path, divided_error, mdy_asy_file,

  File "/isilon/projects/J-003316_Canola-activity-10A/BLgenome/3-dna/AutoHiC/src/assembly/adjust_all_error.py", line 111, in adjust_all_error
    asy_operate.moves_ctg(modified_asy_file, error_tran_info, modified_asy_file)

  File "/isilon/projects/J-003316_Canola-activity-10A/BLgenome/3-dna/AutoHiC/src/assembly/asy_operate.py", line 383, in moves_ctg
    get_ctg_info = self.get_ctg_info(ctg_name=ctg, new_asy_file=assembly_file_path)

  File "/isilon/projects/J-003316_Canola-activity-10A/BLgenome/3-dna/AutoHiC/src/assembly/asy_operate.py", line 131, in get_ctg_info
    return ctg_by_name[ctg_name]

KeyError: '>scaffold00009:::fragment_8'
`
Could you help me check this error and give some suggestions to modify the parameters?
Thanks,
Fuyou

**Comment by Jwindler** [comment]
can you upload your whole `log`, `.hic` and `.asy` file for check ?

**Comment by sunnycqcn** [comment]
Hello Jwindler,
Thanks for your replying.
You can download all files from the linkage:
[https://drive.google.com/drive/folders/0B92oSx9RZqS_fkZDMVRCc19CSkxuRjFyVThoOExMREh4eVBTTTQ1c0h6c2Nhc1RtcGVsSzQ?resourcekey=0-i2eYpLxpKp5_dEnHlB2dVQ&usp=sharing](url)
My genome size is about 45Mb.
Best,
Fuyou

**Comment by Jwindler** [comment]
i see your hic file. i think your fungal scaffold is so bad, so AutoHiC
adjust error maybe wrong. i prefer you to use HapHiC or other scaffolder to scaffolding, then run onehic.py to check.

**Comment by sunnycqcn** [comment]
Thanks,
I will try more.
