### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by Bobo22331** [Jwindler/AutoHiC#49]
Hi,
When I check if the autohic installed via conda is working, an error occurs:
```
(autohic) [cuixb@yls AutoHiC-main]$ python ./autohic.py -h
Traceback (most recent call last):
  File "/raid8/cuixb/tools/biosoft/AutoHiC-main/./autohic.py", line 20, in <module>
    from src.common.error_pd import infer_error
  File "/raid8/cuixb/tools/biosoft/AutoHiC-main/src/common/error_pd.py", line 11, in <module>
    import cv2
  File "/home/cuixb/tools/biosoft/conda3/envs/autohic/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/cuixb/tools/biosoft/conda3/envs/autohic/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/cuixb/tools/biosoft/conda3/envs/autohic/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen: cannot load any more object with static TLS
```
How can I solve this? Thanks a lot.

**Comment by Jwindler** [comment]
> so sorry to tell you, i have not encountered this error. you can refer to [pytorch/pytorch#2575](https://github.com/pytorch/pytorch/issues/2575) and [scikit-learn/scikit-learn#14485](https://github.com/scikit-learn/scikit-learn/issues/14485). in my opinion, you can use docker to solve it. maybe you should reinstall AutoHiC.

maybe you can ref
